### ISSUE TITLE
cross entropy definition

### ISSUE THREAD

**Issue by apyskir** [minerva-ml/steppy#3]
cross_entropy function: https://github.com/neptune-ml/steps/blob/dev/steps/pytorch/validation.py#L24 probably should be defined in a slightly different way:

def cross_entropy(output, target, squeeze=False):
    if squeeze:
        target = target.squeeze(1)
    return F.nll_loss(F.log_softmax(output), target)

Please verify.

**Comment by kamil-kaczmarek** [comment]
moved to steppy-toolkit. Closing.
